import { z } from "zod";

/**
 * API payloads for the participant surface.
 *
 * NOTHING in `lib/schemas/**` may import `server-only`: a client form
 * validates against exactly the same module the Server Action does (PLAN
 * §5.7). Keep this folder free of server imports.
 */

/**
 * The id is generated by the BROWSER (`crypto.randomUUID()` — PLAN §5.14),
 * so it arrives from the client and is validated as a uuid here rather than
 * trusted. It identifies nobody: there is no PII behind it.
 */
export const registerParticipantInput = z.object({
  participantId: z.uuid(),
  /** The `/b/{token}` they arrived through, recorded as `entry_batch`. */
  batchToken: z.string().min(1).optional(),
  /** Live sessions only, and optional there too. */
  displayName: z.string().trim().min(1).max(80).optional(),
});
export type RegisterParticipantInput = z.infer<typeof registerParticipantInput>;
